# Generated by Django 2.2.12 on 2022-03-08 18:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=core.models.file_path)),
                ('filename', models.CharField(default='0000000', max_length=500)),
                ('file_version', models.FloatField()),
            ],
        ),
    ]
