# Generated by Django 2.2.12 on 2022-03-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehandler',
            name='filename',
        ),
        migrations.AddField(
            model_name='filehandler',
            name='file_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
