# Generated by Django 2.2.12 on 2022-03-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220308_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandler',
            name='file_version',
            field=models.FloatField(default=''),
        ),
    ]
