# Generated by Django 2.2.13 on 2022-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220309_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehandler',
            name='file_version',
        ),
    ]
